﻿// This file was auto-generated by ML.NET Model Builder. 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers.LightGbm;
using Microsoft.ML.Trainers;
using Microsoft.ML;

namespace MinesweeperML_NET
{
    public partial class MLModel1
    {
        public static ITransformer RetrainPipeline(MLContext context, IDataView trainData)
        {
            var pipeline = BuildPipeline(context);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.ReplaceMissingValues(new []{new InputOutputColumnPair(@"in-u2l2", @"in-u2l2"),new InputOutputColumnPair(@"in-u2l1", @"in-u2l1"),new InputOutputColumnPair(@"in-u2", @"in-u2"),new InputOutputColumnPair(@"in-u2r1", @"in-u2r1"),new InputOutputColumnPair(@"in-u2r2", @"in-u2r2"),new InputOutputColumnPair(@"in-u1l2", @"in-u1l2"),new InputOutputColumnPair(@"in-u1l1", @"in-u1l1"),new InputOutputColumnPair(@"in-u1", @"in-u1"),new InputOutputColumnPair(@"in-u1r1", @"in-u1r1"),new InputOutputColumnPair(@"in-u1r2", @"in-u1r2"),new InputOutputColumnPair(@"in-l2", @"in-l2"),new InputOutputColumnPair(@"in-l1", @"in-l1"),new InputOutputColumnPair(@"in-0", @"in-0"),new InputOutputColumnPair(@"in-r1", @"in-r1"),new InputOutputColumnPair(@"in-r2", @"in-r2"),new InputOutputColumnPair(@"in-d1l2", @"in-d1l2"),new InputOutputColumnPair(@"in-d1l1", @"in-d1l1"),new InputOutputColumnPair(@"in-d1", @"in-d1"),new InputOutputColumnPair(@"in-d1r1", @"in-d1r1"),new InputOutputColumnPair(@"in-d1r2", @"in-d1r2"),new InputOutputColumnPair(@"in-d2l2", @"in-d2l2"),new InputOutputColumnPair(@"in-d2l1", @"in-d2l1"),new InputOutputColumnPair(@"in-d2", @"in-d2"),new InputOutputColumnPair(@"in-d2r1", @"in-d2r1"),new InputOutputColumnPair(@"in-d2r2", @"in-d2r2")})      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"in-u2l2",@"in-u2l1",@"in-u2",@"in-u2r1",@"in-u2r2",@"in-u1l2",@"in-u1l1",@"in-u1",@"in-u1r1",@"in-u1r2",@"in-l2",@"in-l1",@"in-0",@"in-r1",@"in-r2",@"in-d1l2",@"in-d1l1",@"in-d1",@"in-d1r1",@"in-d1r2",@"in-d2l2",@"in-d2l1",@"in-d2",@"in-d2r1",@"in-d2r2"}))      
                                    .Append(mlContext.Transforms.Conversion.MapValueToKey(@"out", @"out"))      
                                    .Append(mlContext.MulticlassClassification.Trainers.LightGbm(new LightGbmMulticlassTrainer.Options(){NumberOfLeaves=4,MinimumExampleCountPerLeaf=2,NumberOfIterations=12811,MaximumBinCountPerFeature=8,LearningRate=0.000210619083288141F,LabelColumnName=@"out",FeatureColumnName=@"Features",Booster=new GradientBooster.Options(){SubsampleFraction=0.733826827505467F,FeatureFraction=1F,L1Regularization=2E-10F,L2Regularization=313.14436231742F}}))      
                                    .Append(mlContext.Transforms.Conversion.MapKeyToValue(@"PredictedLabel", @"PredictedLabel"));

            return pipeline;
        }
    }
}
